### ISSUE TITLE
Vidéo quality

### ISSUE THREAD

**Issue by dellas60** [Troikano/plugin.video.vk2#1]
Can you add  option to select vidéo quality because i have a poor internet connection,and i would Ask if hls select automaticaly vidéo quality that Sync with internet debit,thanks.

**Comment by Troikano** [comment]
Normally the hls stream selects the quality depending on the connection. However you can check and change the video bitrate as in the following image.
![Screenshot from 2021-12-13 23-39-19_1](https://user-images.githubusercontent.com/26659085/145906901-a4b20255-1631-49dd-a762-fc3545501823.jpeg)
![Screenshot from 2021-12-13 23-39-35_2](https://user-images.githubusercontent.com/26659085/145906902-bba7e8b1-5586-4adb-aeb4-50bc100d13a6.jpeg)
