### ISSUE TITLE
This great plugin does not work anymore, will it ever be fixed?

### ISSUE THREAD

**Issue by Krando** [Troikano/plugin.video.vk2#2]
This was a fantastic plugin which I came across when I was looking for a way to search for videos through a GUI using VK's API. I installed it but it doesn't work. When you type in your email/phone number or password, it just keeps loading and nothing happens and eventually you get an error. If the main developer (Troikano) replies to this message, I will provide him the error log. Note that I am using Python 3.8.x.

I really want this plugin to work, nothing exists like it elsewhere.

**Comment by Troikano** [comment]
Can you send me the log, please?

Does the error happen when you click on a video or when you login? thanks =)

**Comment by Krando** [comment]
Troikano, thank you very much for your reply. Apparently there is nothing wrong with this plugin, it works wonderfully. The problem was with my network, VK was denying my connection to oauth.vk.com. When I switched to a different network, the problem was solved.
